language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-19.1.0
    - android-20
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
  license:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
